# Generated by Django 4.2.7 on 2025-12-13 15:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Para el listado de servicios', max_length=200, verbose_name='Descripción corta')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción completa')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fa-solid fa-hammer)', max_length=100, verbose_name='Icono CSS')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description (SEO)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'title'],
            },
        ),
    ]
