# Generated by Django 4.2.7 on 2026-01-04 17:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('short_description', models.TextField(help_text='Para el listado de servicios', max_length=200, verbose_name='Descripción corta')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción completa')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description (SEO)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service')),
            ],
            options={
                'verbose_name': 'Servicio Translation',
                'db_table': 'services_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
