# Generated by Django 4.2.7 on 2026-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE services_service_translation ALTER COLUMN description TYPE text;",
            reverse_sql="ALTER TABLE services_service_translation ALTER COLUMN description TYPE text;",
        ),
    ]
