# Generated by Django 4.2.7 on 2026-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE blog_post_translation ALTER COLUMN content TYPE text;",
            reverse_sql="ALTER TABLE blog_post_translation ALTER COLUMN content TYPE text;",
        ),
    ]
