# Generated by Django 4.2.7 on 2025-12-13 15:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fa-solid fa-heart)', max_length=100, verbose_name='Icono CSS')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Valor de la Empresa',
                'verbose_name_plural': 'Valores de la Empresa',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('meta_title', models.CharField(blank=True, help_text='Si está vacío, se usará el título de la página', max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, help_text='Si está vacío, se usará un extracto del contenido', max_length=160, verbose_name='Meta Description (SEO)')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='Imagen Open Graph')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo/Posición')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización en la página', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['order', 'name'],
            },
        ),
    ]
