# Generated by Django 4.2.7 on 2026-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_options_remove_companyvalue_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_page_translation ALTER COLUMN content TYPE text;",
            reverse_sql="ALTER TABLE core_page_translation ALTER COLUMN content TYPE text;",
        ),
    ]
