# Generated by Django 4.2.7 on 2026-02-02 18:08

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('piso', 'Piso'), ('apartamento', 'Apartamento'), ('local', 'Local Comercial'), ('terreno', 'Terreno')], default='casa', max_length=20, verbose_name='Tipo de propiedad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('surface_area', models.PositiveIntegerField(verbose_name='Superficie (m²)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('location', models.CharField(help_text='Ciudad o zona (ej: Palma de Mallorca)', max_length=200, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Vendido')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparecerá en la página principal', verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción completa')),
                ('short_description', models.TextField(help_text='Descripción breve para listados', max_length=300, verbose_name='Resumen')),
                ('features', models.TextField(blank=True, help_text='Piscina, garaje, terraza, etc. (una por línea)', verbose_name='Características')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description (SEO)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Propiedad Translation',
                'db_table': 'properties_property_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
